name: cd workflow

on:
  push:
    branches:
      - master
    
jobs:
 deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1