name: Main workflow

on: push

jobs:
 eslint:
   name: ESLint
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code  
        uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
 test:
   name: Test
   runs-on: ubuntu-latest
   needs: eslint
   steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
 build:
   name: Build
   runs-on: ubuntu-latest
   needs: test
   steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
 deploy:
   name: Deploy
   runs-on: ubuntu-latest
   needs: build
   if: github.ref == 'refs/heads/master'

   steps:
      - uses: actions/checkout@v2
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1