name: Main workflow

on: push

jobs:
 eslint:
   name: ESLint
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code  
        uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
 build:
   name: Build
   runs-on: ubuntu-latest
   needs:  eslint
   steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run : yarn install
      - name: Build
        run: yarn build
 test:
   name: Test
   runs-on: ubuntu-latest
   needs: build
   steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run : yarn install
      - name: Run tests
        run: yarn test
 deploy:
   name: Deploy
   runs-on: ubuntu-latest
   needs: test
   if: github.ref == 'refs/heads/master'

   steps:
      - uses: actions/checkout@v2
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1